// Livros que ampliam o catálogo inicial: título e autor como a Open Library conhece,
// título em português, gêneros e uma sinopse curta, sem spoiler.
export const EXTRA = [
  // Literatura brasileira
  { title: "O Cortiço", author: "Aluísio Azevedo", pt: "O Cortiço", genres: ["Clássico", "Literatura brasileira"], synopsis: "Um cortiço no Rio do século XIX cresce como um bicho vivo, e com ele a ambição de João Romão. O Naturalismo brasileiro em seu retrato mais cru." },
  { title: "Iracema", author: "José de Alencar", pt: "Iracema", genres: ["Clássico", "Literatura brasileira"], synopsis: "A virgem dos lábios de mel e o colonizador português num romance-poema sobre o nascimento do Ceará e de um povo." },
  { title: "Macunaíma", author: "Mário de Andrade", pt: "Macunaíma", genres: ["Clássico", "Literatura brasileira"], synopsis: "O herói sem nenhum caráter sai da floresta para São Paulo atrás de um amuleto. Rapsódia modernista, engraçada e cheia de Brasil." },
  { title: "A Paixão segundo G.H.", author: "Clarice Lispector", pt: "A Paixão segundo G.H.", genres: ["Literatura brasileira", "Clássico"], synopsis: "Uma mulher entra no quarto da empregada e encontra uma barata. O que vem depois é uma das experiências mais radicais da literatura." },
  { title: "Quincas Borba", author: "Machado de Assis", pt: "Quincas Borba", genres: ["Clássico", "Literatura brasileira"], synopsis: "Rubião herda a fortuna e a filosofia de um amigo louco e vai para a Corte. Ao vencedor, as batatas." },
  { title: "O Quinze", author: "Rachel de Queiroz", pt: "O Quinze", genres: ["Clássico", "Literatura brasileira"], synopsis: "A seca de 1915 no Ceará vista por quem fica e por quem precisa partir. Estreia de Rachel de Queiroz, aos vinte anos." },
  { title: "Gabriela, Cravo e Canela", author: "Jorge Amado", pt: "Gabriela, Cravo e Canela", genres: ["Literatura brasileira", "Romance"], synopsis: "Ilhéus, 1925: o cacau enriquece a cidade e Gabriela chega para mudar a cozinha e o coração de Nacib." },
  { title: "Dona Flor e Seus Dois Maridos", author: "Jorge Amado", work: "OL1248164W", pt: "Dona Flor e Seus Dois Maridos", genres: ["Literatura brasileira", "Realismo mágico"], synopsis: "Viúva de um boêmio, Flor casa com um farmacêutico certinho. Até que o primeiro marido resolve voltar." },
  { title: "São Bernardo", author: "Graciliano Ramos", pt: "São Bernardo", genres: ["Clássico", "Literatura brasileira"], synopsis: "Paulo Honório conquistou a fazenda a qualquer custo. Agora tenta escrever a própria história e entender o que perdeu." },
  { title: "Quarto de Despejo", author: "Carolina Maria de Jesus", pt: "Quarto de Despejo", genres: ["Não ficção", "Literatura brasileira"], synopsis: "O diário de uma catadora de papel na favela do Canindé. A fome, a escrita e uma voz que o Brasil não queria ouvir." },
  { title: "Lavoura Arcaica", author: "Raduan Nassar", pt: "Lavoura Arcaica", genres: ["Literatura brasileira", "Romance curto"], synopsis: "André foge da casa do pai e o irmão vai buscá-lo. Uma prosa que queima, sobre família, desejo e lei." },
  { title: "O Avesso da Pele", author: "Jeferson Tenório", pt: "O Avesso da Pele", genres: ["Literatura brasileira", "Contemporâneo"], synopsis: "Pedro reconstrói a vida do pai, professor negro morto numa abordagem policial. Um livro sobre memória e racismo." },
  { title: "Cidade de Deus", author: "Paulo Lins", pt: "Cidade de Deus", genres: ["Literatura brasileira", "Contemporâneo"], synopsis: "Três décadas de um conjunto habitacional no Rio, da malandragem ao tráfico. O romance que virou o filme." },
  { title: "Triste Fim de Policarpo Quaresma", author: "Lima Barreto", pt: "Triste Fim de Policarpo Quaresma", genres: ["Clássico", "Literatura brasileira"], synopsis: "Um patriota ingênuo quer o tupi como língua oficial. Sátira amarga sobre o Brasil da Primeira República." },
  { title: "Sagarana", author: "João Guimarães Rosa", pt: "Sagarana", genres: ["Clássico", "Literatura brasileira", "Contos"], synopsis: "Nove contos do sertão mineiro, com burrinhos, valentões e feiticeiros. A estreia de Guimarães Rosa." },
  { title: "O Continente", author: "Erico Verissimo", pt: "O Tempo e o Vento: O Continente", genres: ["Literatura brasileira", "Romance histórico"], synopsis: "Ana Terra, o capitão Rodrigo e a fundação de Santa Fé. Primeira parte da saga gaúcha de Erico Verissimo." },
  { title: "Laços de Família", author: "Clarice Lispector", pt: "Laços de Família", genres: ["Literatura brasileira", "Contos"], synopsis: "Uma galinha, um cego mascando chiclete, um aniversário de família. Contos em que o cotidiano racha de repente." },

  // América Latina
  { title: "Pedro Páramo", author: "Juan Rulfo", pt: "Pedro Páramo", genres: ["Clássico", "Literatura latino-americana"], synopsis: "Juan Preciado vai a Comala procurar o pai e encontra um povoado de vozes e de mortos. Curto e inesquecível." },
  { title: "Ficciones", author: "Jorge Luis Borges", pt: "Ficções", genres: ["Clássico", "Literatura latino-americana", "Contos"], synopsis: "Bibliotecas infinitas, mapas do tamanho do império, livros que se bifurcam. Os contos que mudaram a ficção." },
  { title: "La casa de los espíritus", author: "Isabel Allende", pt: "A Casa dos Espíritos", genres: ["Literatura latino-americana", "Realismo mágico"], synopsis: "Quatro gerações da família Trueba, entre amores, fantasmas e a história política de um país latino-americano." },
  { title: "Rayuela", author: "Julio Cortázar", pt: "O Jogo da Amarelinha", genres: ["Clássico", "Literatura latino-americana"], synopsis: "Um romance que se lê em mais de uma ordem. Paris, Buenos Aires e a busca de Oliveira pela Maga." },
  { title: "El amor en los tiempos del cólera", author: "Gabriel García Márquez", pt: "O Amor nos Tempos do Cólera", genres: ["Literatura latino-americana", "Romance"], synopsis: "Florentino espera mais de cinquenta anos por Fermina. Um amor teimoso numa cidade do Caribe." },

  // Clássicos
  { title: "Jane Eyre", author: "Charlotte Brontë", pt: "Jane Eyre", genres: ["Clássico", "Romance"], synopsis: "Órfã e preceptora, Jane chega a Thornfield e ao senhor Rochester. Uma heroína que não abre mão de si." },
  { title: "Wuthering Heights", author: "Emily Brontë", pt: "O Morro dos Ventos Uivantes", genres: ["Clássico", "Romance"], synopsis: "Heathcliff e Catherine num amor que vira obsessão e vingança, nas charnecas de Yorkshire." },
  { title: "Moby Dick", author: "Herman Melville", pt: "Moby Dick", genres: ["Clássico", "Aventura"], synopsis: "Me chamem de Ismael. O capitão Ahab arrasta a tripulação atrás da baleia branca." },
  { title: "Anna Karenina", author: "Leo Tolstoy", work: "OL267096W", pt: "Anna Kariênina", genres: ["Clássico", "Literatura russa"], synopsis: "Uma mulher da alta sociedade russa se apaixona e desafia tudo. Ao lado, Liévin procura sentido no campo." },
  { title: "The Brothers Karamazov", author: "Fyodor Dostoevsky", pt: "Os Irmãos Karamázov", genres: ["Clássico", "Literatura russa"], synopsis: "Três irmãos, um pai detestável e um crime. Fé, dúvida e liberdade no último romance de Dostoiévski." },
  { title: "Madame Bovary", author: "Gustave Flaubert", pt: "Madame Bovary", genres: ["Clássico", "Romance"], synopsis: "Emma sonha com a vida dos romances e se casa com um médico de província. O tédio cobra caro." },
  { title: "Les Misérables", author: "Victor Hugo", pt: "Os Miseráveis", genres: ["Clássico", "Romance histórico"], synopsis: "Jean Valjean sai da prisão e tenta recomeçar, perseguido por Javert, numa França de fome e barricadas." },
  { title: "Don Quixote", author: "Miguel de Cervantes", pt: "Dom Quixote", genres: ["Clássico", "Aventura"], synopsis: "Um fidalgo lê romances de cavalaria demais e sai pelo mundo com Sancho Pança. O primeiro romance moderno." },
  { title: "The Picture of Dorian Gray", author: "Oscar Wilde", pt: "O Retrato de Dorian Gray", genres: ["Clássico", "Terror"], synopsis: "Dorian não envelhece; o retrato dele, sim. Beleza, culpa e frases que todo mundo cita." },
  { title: "Dracula", author: "Bram Stoker", pt: "Drácula", genres: ["Clássico", "Terror"], synopsis: "Cartas e diários contam a viagem de Jonathan Harker à Transilvânia e o que vem atrás dele até Londres." },
  { title: "Little Women", author: "Louisa May Alcott", pt: "Mulherzinhas", genres: ["Clássico", "Romance"], synopsis: "Meg, Jo, Beth e Amy crescem durante a Guerra Civil americana, cada uma do seu jeito." },
  { title: "Of Mice and Men", author: "John Steinbeck", pt: "Ratos e Homens", genres: ["Clássico", "Novela"], synopsis: "George e Lennie sonham com um pedaço de terra durante a Grande Depressão. Breve e devastador." },
  { title: "The Catcher in the Rye", author: "J. D. Salinger", pt: "O Apanhador no Campo de Centeio", genres: ["Clássico", "Juvenil"], synopsis: "Expulso da escola, Holden Caulfield passa dias vagando por Nova York e odiando tudo que é falso." },
  { title: "Animal Farm", author: "George Orwell", pt: "A Revolução dos Bichos", genres: ["Clássico", "Fábula"], synopsis: "Os animais expulsam o fazendeiro e criam uma sociedade de iguais. Alguns, porém, são mais iguais que outros." },
  { title: "Fahrenheit 451", author: "Ray Bradbury", pt: "Fahrenheit 451", genres: ["Distopia", "Clássico"], synopsis: "Montag é bombeiro: queima livros. Até que começa a ler um deles." },
  { title: "L'Étranger", author: "Albert Camus", pt: "O Estrangeiro", genres: ["Clássico", "Romance curto"], synopsis: "Hoje, mamãe morreu. Meursault atravessa a vida sem fingir o que não sente, e isso tem um preço." },
  { title: "Mrs Dalloway", author: "Virginia Woolf", pt: "Mrs. Dalloway", genres: ["Clássico", "Romance"], synopsis: "Um dia em Londres: Clarissa prepara uma festa, e a cidade inteira passa pela cabeça dela." },
  { title: "Beloved", author: "Toni Morrison", pt: "Amada", genres: ["Clássico", "Romance histórico"], synopsis: "Sethe escapou da escravidão, mas a casa em Ohio continua assombrada pelo passado." },
  { title: "Os Maias", author: "Eça de Queirós", pt: "Os Maias", genres: ["Clássico", "Literatura portuguesa"], synopsis: "A decadência de uma família lisboeta e um amor que não podia acontecer. O grande romance de Eça." },
  { title: "Siddhartha", author: "Hermann Hesse", pt: "Sidarta", genres: ["Clássico", "Romance curto"], synopsis: "Um jovem brâmane deixa tudo para buscar a iluminação pelo próprio caminho." },
  { title: "The Bell Jar", author: "Sylvia Plath", pt: "A Redoma de Vidro", genres: ["Clássico", "Romance"], synopsis: "Esther ganha um estágio em Nova York e sente o mundo se fechar como uma redoma." },
  { title: "Things Fall Apart", author: "Chinua Achebe", pt: "O Mundo se Despedaça", genres: ["Clássico", "Literatura africana"], synopsis: "Okonkwo é respeitado em sua aldeia igbo até a chegada dos missionários e do império britânico." },

  // Fantasia
  { title: "The Fellowship of the Ring", author: "J.R.R. Tolkien", pt: "O Senhor dos Anéis: A Sociedade do Anel", genres: ["Fantasia", "Aventura"], synopsis: "Frodo herda um anel e precisa levá-lo para longe do Condado. Começa a jornada mais famosa da fantasia." },
  { title: "A Game of Thrones", author: "George R. R. Martin", pt: "A Guerra dos Tronos", genres: ["Fantasia"], synopsis: "O inverno está chegando, e as grandes casas de Westeros disputam o Trono de Ferro. Ninguém está seguro." },
  { title: "The Lion, the Witch and the Wardrobe", author: "C. S. Lewis", pt: "O Leão, a Feiticeira e o Guarda-Roupa", genres: ["Fantasia", "Juvenil"], synopsis: "Quatro irmãos atravessam um guarda-roupa e chegam a Nárnia, presa num inverno sem Natal." },
  { title: "Mistborn: The Final Empire", author: "Brandon Sanderson", work: "OL5738148W", pt: "Mistborn: O Império Final", genres: ["Fantasia", "Aventura"], synopsis: "Num mundo de cinzas governado por um deus imortal, uma ladra descobre que pode queimar metais e ganha poderes." },
  { title: "American Gods", author: "Neil Gaiman", pt: "Deuses Americanos", genres: ["Fantasia", "Contemporâneo"], synopsis: "Shadow sai da prisão e vira guarda-costas de um homem misterioso, numa guerra entre deuses antigos e novos." },
  { title: "Good Omens", author: "Terry Pratchett", pt: "Belas Maldições", genres: ["Fantasia", "Humor"], synopsis: "Um anjo e um demônio, amigos há seis mil anos, tentam evitar o Apocalipse. Perderam o Anticristo." },
  { title: "A Court of Thorns and Roses", author: "Sarah J. Maas", pt: "Corte de Espinhos e Rosas", genres: ["Fantasia", "Romance"], synopsis: "Feyre mata um lobo na floresta e paga com a liberdade: é levada para Prythian, a terra dos feéricos." },
  { title: "The Lightning Thief", author: "Rick Riordan", pt: "Percy Jackson e o Ladrão de Raios", genres: ["Fantasia", "Juvenil"], synopsis: "Percy descobre que é filho de um deus grego e é acusado de roubar o raio de Zeus." },
  { title: "Fourth Wing", author: "Rebecca Yarros", pt: "Quarta Asa", genres: ["Fantasia", "Romance"], synopsis: "Violet é jogada na escola de cavaleiros de dragões, onde sobreviver já é uma vitória." },
  { title: "Circe", author: "Madeline Miller", pt: "Circe", genres: ["Fantasia", "Mitologia"], synopsis: "A feiticeira da Odisseia conta sua própria história: exílio, poder e os homens que passam pela ilha." },
  { title: "The Song of Achilles", author: "Madeline Miller", pt: "A Canção de Aquiles", genres: ["Mitologia", "Romance"], synopsis: "Pátroclo conta como conheceu Aquiles e o seguiu até Troia." },

  // Ficção científica e distopia
  { title: "Foundation", author: "Isaac Asimov", pt: "Fundação", genres: ["Ficção científica", "Clássico"], synopsis: "Um matemático prevê a queda do Império Galáctico e planeja encurtar a idade das trevas que vem depois." },
  { title: "The Martian", author: "Andy Weir", pt: "Perdido em Marte", genres: ["Ficção científica", "Aventura"], synopsis: "Deixado para trás em Marte, um astronauta botânico precisa sobreviver com ciência e bom humor." },
  { title: "Neuromancer", author: "William Gibson", pt: "Neuromancer", genres: ["Ficção científica"], synopsis: "Um hacker decadente é contratado para um último trabalho no ciberespaço. O livro que inventou o cyberpunk." },
  { title: "The Left Hand of Darkness", author: "Ursula K. Le Guin", pt: "A Mão Esquerda da Escuridão", genres: ["Ficção científica", "Clássico"], synopsis: "Um enviado chega a um planeta gelado onde as pessoas não têm gênero fixo." },
  { title: "Do Androids Dream of Electric Sheep?", author: "Philip K. Dick", pt: "Androides Sonham com Ovelhas Elétricas?", genres: ["Ficção científica", "Clássico"], synopsis: "Rick Deckard caça androides numa Terra em ruínas e começa a duvidar do que é ser humano." },
  { title: "The Hitchhiker's Guide to the Galaxy", author: "Douglas Adams", pt: "O Guia do Mochileiro das Galáxias", genres: ["Ficção científica", "Humor"], synopsis: "A Terra é demolida para dar lugar a uma via expressa. Arthur Dent pega carona com um amigo alienígena." },
  { title: "Ender's Game", author: "Orson Scott Card", pt: "O Jogo do Exterminador", genres: ["Ficção científica", "Juvenil"], synopsis: "Crianças são treinadas em jogos de guerra para enfrentar uma invasão alienígena. Ender é o melhor deles." },
  { title: "Klara and the Sun", author: "Kazuo Ishiguro", pt: "Klara e o Sol", genres: ["Ficção científica", "Contemporâneo"], synopsis: "Klara é uma amiga artificial que observa o mundo da vitrine e depois da casa de uma menina doente." },
  { title: "The Handmaid's Tale", author: "Margaret Atwood", pt: "O Conto da Aia", genres: ["Distopia", "Clássico"], synopsis: "Na República de Gilead, Offred existe para gerar filhos. Ela lembra de quando era outra pessoa." },
  { title: "The Hunger Games", author: "Suzanne Collins", pt: "Jogos Vorazes", genres: ["Distopia", "Juvenil"], synopsis: "Katniss se oferece no lugar da irmã para um jogo televisionado em que só um sai vivo." },

  // Mistério e suspense
  { title: "And Then There Were None", author: "Agatha Christie", pt: "E Não Sobrou Nenhum", genres: ["Mistério", "Clássico"], synopsis: "Dez desconhecidos numa ilha, um a um acusados de um crime do passado. E um a um, morrendo." },
  { title: "Murder on the Orient Express", author: "Agatha Christie", pt: "Assassinato no Expresso do Oriente", genres: ["Mistério", "Clássico"], synopsis: "O trem para na neve e um passageiro aparece morto. Hercule Poirot tem doze suspeitos." },
  { title: "Gone Girl", author: "Gillian Flynn", pt: "Garota Exemplar", genres: ["Suspense"], synopsis: "No aniversário de casamento, Amy desaparece. Nick vira o principal suspeito, e o diário dela conta outra história." },
  { title: "The Girl with the Dragon Tattoo", author: "Stieg Larsson", work: "OL5784622W", pt: "Os Homens que Não Amavam as Mulheres", genres: ["Suspense", "Mistério"], synopsis: "Um jornalista e a hacker Lisbeth Salander investigam o sumiço de uma jovem quarenta anos atrás." },
  { title: "The Silent Patient", author: "Alex Michaelides", pt: "A Paciente Silenciosa", genres: ["Suspense"], synopsis: "Alicia atira cinco vezes no marido e nunca mais fala. Um psicoterapeuta decide fazê-la falar." },
  { title: "The Da Vinci Code", author: "Dan Brown", pt: "O Código Da Vinci", genres: ["Suspense", "Mistério"], synopsis: "Um assassinato no Louvre deixa pistas nas obras de Leonardo. Robert Langdon corre contra o tempo." },
  { title: "The Hound of the Baskervilles", author: "Arthur Conan Doyle", pt: "O Cão dos Baskervilles", genres: ["Mistério", "Clássico"], synopsis: "Uma maldição de família, um cão infernal nas charnecas e Sherlock Holmes duvidando de tudo." },

  // Terror
  { title: "It", author: "Stephen King", pt: "A Coisa", genres: ["Terror"], synopsis: "Em Derry, algo acorda a cada 27 anos. Sete amigos prometeram voltar se ele voltasse." },
  { title: "The Shining", author: "Stephen King", pt: "O Iluminado", genres: ["Terror", "Clássico"], synopsis: "Jack aceita cuidar de um hotel isolado durante o inverno, com a esposa e o filho que vê coisas." },
  { title: "Mexican Gothic", author: "Silvia Moreno-Garcia", pt: "Gótico Mexicano", genres: ["Terror", "Mistério"], synopsis: "Noemí vai a uma mansão decadente nas montanhas do México para ajudar a prima, que escreveu uma carta estranha." },
  { title: "Coraline", author: "Neil Gaiman", pt: "Coraline", genres: ["Terror", "Juvenil"], synopsis: "Atrás de uma porta, Coraline encontra uma casa igual à dela, com uma outra mãe que tem botões no lugar dos olhos." },

  // Romance e contemporâneos
  { title: "Me Before You", author: "Jojo Moyes", pt: "Como Eu Era Antes de Você", genres: ["Romance", "Contemporâneo"], synopsis: "Lou vira cuidadora de Will, que ficou tetraplégico e perdeu a vontade de viver." },
  { title: "It Ends with Us", author: "Colleen Hoover", pt: "É Assim que Acaba", genres: ["Romance", "Contemporâneo"], synopsis: "Lily se apaixona por um neurocirurgião em Boston, até que um amor antigo reaparece." },
  { title: "Normal People", author: "Sally Rooney", pt: "Pessoas Normais", genres: ["Romance", "Contemporâneo"], synopsis: "Connell e Marianne se aproximam no colégio e se perdem e se reencontram pelos anos seguintes." },
  { title: "The Fault in Our Stars", author: "John Green", pt: "A Culpa É das Estrelas", genres: ["Romance", "Juvenil"], synopsis: "Hazel e Augustus se conhecem num grupo de apoio para jovens com câncer." },
  { title: "Daisy Jones & The Six", author: "Taylor Jenkins Reid", pt: "Daisy Jones & The Six", genres: ["Contemporâneo", "Romance"], synopsis: "Em forma de entrevistas, a ascensão e o fim de uma banda de rock dos anos 70." },
  { title: "The Book Thief", author: "Markus Zusak", pt: "A Menina que Roubava Livros", genres: ["Romance histórico", "Juvenil"], synopsis: "Na Alemanha nazista, Liesel rouba livros e os lê para os vizinhos no porão. A Morte narra." },
  { title: "The Kite Runner", author: "Khaled Hosseini", pt: "O Caçador de Pipas", genres: ["Contemporâneo", "Romance"], synopsis: "Amir cresceu em Cabul com o amigo Hassan e uma traição que nunca esqueceu." },
  { title: "Eleanor Oliphant Is Completely Fine", author: "Gail Honeyman", pt: "Eleanor Oliphant Está Muito Bem", genres: ["Contemporâneo"], synopsis: "Eleanor tem a mesma rotina todo dia e acha que está ótima. Um colega de trabalho começa a mudar isso." },
  { title: "Where the Crawdads Sing", author: "Delia Owens", pt: "Um Lugar Bem Longe Daqui", genres: ["Mistério", "Romance"], synopsis: "Kya cresceu sozinha no pântano. Quando um rapaz da cidade aparece morto, todos olham para ela." },
  { title: "Americanah", author: "Chimamanda Ngozi Adichie", pt: "Americanah", genres: ["Contemporâneo", "Literatura africana"], synopsis: "Ifemelu deixa a Nigéria pelos Estados Unidos e descobre o que é ser negra lá. Anos depois, decide voltar." },

  // Literatura asiática
  { title: "Kafka on the Shore", author: "Haruki Murakami", work: "OL2625431W", pt: "Kafka à Beira-Mar", genres: ["Literatura japonesa", "Realismo mágico"], synopsis: "Um garoto foge de casa aos quinze anos; um velho que fala com gatos começa uma viagem. Os caminhos se cruzam." },
  { title: "Convenience Store Woman", author: "Sayaka Murata", pt: "Querida Konbini", genres: ["Literatura japonesa", "Contemporâneo"], synopsis: "Keiko trabalha há dezoito anos numa loja de conveniência e é feliz assim. Os outros não aceitam." },
  { title: "The Vegetarian", author: "Han Kang", work: "OL17334243W", pt: "A Vegetariana", genres: ["Literatura coreana", "Contemporâneo"], synopsis: "Depois de um sonho, Yeong-hye para de comer carne. A família não perdoa." },
  { title: "Before the Coffee Gets Cold", author: "Toshikazu Kawaguchi", pt: "Antes que o Café Esfrie", genres: ["Literatura japonesa", "Fantasia"], synopsis: "Num café de Tóquio, uma cadeira leva ao passado, mas só até o café esfriar." },
  { title: "No Longer Human", author: "Osamu Dazai", pt: "Indigno de Ser Humano", genres: ["Literatura japonesa", "Clássico"], synopsis: "Os cadernos de um homem que nunca soube viver entre os outros e decidiu fazer palhaçada." },

  // Não ficção
  { title: "Thinking, Fast and Slow", author: "Daniel Kahneman", pt: "Rápido e Devagar", genres: ["Não ficção", "Psicologia"], synopsis: "Os dois sistemas da mente, o intuitivo e o deliberado, e os erros que eles nos fazem cometer." },
  { title: "Atomic Habits", author: "James Clear", pt: "Hábitos Atômicos", genres: ["Não ficção", "Autoajuda"], synopsis: "Pequenas mudanças, repetidas, que somam grandes resultados. Um método prático para criar e largar hábitos." },
  { title: "Het Achterhuis", author: "Anne Frank", pt: "O Diário de Anne Frank", genres: ["Não ficção", "História"], synopsis: "Dois anos escondida num anexo em Amsterdã, contados por uma adolescente que queria ser escritora." },
  { title: "Man's Search for Meaning", author: "Viktor E. Frankl", work: "OL1268413W", pt: "Em Busca de Sentido", genres: ["Não ficção", "Psicologia"], synopsis: "Um psiquiatra sobrevive aos campos de concentração e conta o que aprendeu sobre o sentido da vida." },
  { title: "A Brief History of Time", author: "Stephen Hawking", pt: "Uma Breve História do Tempo", genres: ["Não ficção", "Ciência"], synopsis: "Do Big Bang aos buracos negros, o universo explicado para quem não é físico." },
  { title: "Educated", author: "Tara Westover", pt: "A Menina da Montanha", genres: ["Não ficção", "Biografia"], synopsis: "Criada sem escola nas montanhas de Idaho, Tara entra na faculdade aos dezessete anos e chega a Cambridge." },
  { title: "Ideias para adiar o fim do mundo", author: "Ailton Krenak", pt: "Ideias para Adiar o Fim do Mundo", genres: ["Não ficção"], synopsis: "Ailton Krenak questiona a ideia de humanidade que nos separa da Terra. Pequeno e enorme." },
  { title: "Becoming", author: "Michelle Obama", pt: "Minha História", genres: ["Não ficção", "Biografia"], synopsis: "Da infância em Chicago à Casa Branca, a ex-primeira-dama conta a própria trajetória." },
  { title: "Homo Deus", author: "Yuval Noah Harari", work: "OL17641518W", pt: "Homo Deus", genres: ["Não ficção", "História"], synopsis: "Depois de vencer fome, peste e guerra, o que a humanidade vai querer? Harari olha para o futuro." },

  // Quadrinhos e poesia
  { title: "Maus", author: "Art Spiegelman", pt: "Maus", genres: ["Quadrinhos", "História"], synopsis: "Ratos e gatos contam a história do pai do autor, sobrevivente de Auschwitz. O quadrinho que ganhou o Pulitzer." },
  { title: "Persepolis", author: "Marjane Satrapi", work: "OL5735174W", pt: "Persépolis", genres: ["Quadrinhos", "Biografia"], synopsis: "A infância de Marjane no Irã da revolução islâmica, em preto e branco e com muito humor." },
  { title: "Watchmen", author: "Alan Moore", pt: "Watchmen", genres: ["Quadrinhos", "Ficção científica"], synopsis: "Super-heróis aposentados, a Guerra Fria e um assassinato. Quem vigia os vigilantes?" },
  { title: "Mensagem", author: "Fernando Pessoa", pt: "Mensagem", genres: ["Poesia", "Literatura portuguesa"], synopsis: "O único livro de poemas que Pessoa publicou em português em vida: Portugal, o mar e o mito." },
  { title: "Milk and Honey", author: "Rupi Kaur", pt: "Outros Jeitos de Usar a Boca", genres: ["Poesia", "Contemporâneo"], synopsis: "Poemas curtos sobre amor, perda, trauma e cura, com desenhos da autora." },
];
